### PR TITLE
[WPA-27462]: Add new magenta 50 color

### PR DESCRIPTION
**Pull request by crthc**
Hello!

By merging this PR, we are adding the new magenta 50 color: #F72585

Thanks!

### CODE REVIEW

**Comment by egm77** [comment]
After talk about the missing colours in the Web Styleguide I think you should let @mtempranoWalla know that is missing this colour

**Review by egm77 — APPROVED** [review]

**Review by atomasaltes — APPROVED** [review]

**Comment by atomasaltes** [comment]
> After talk about the missing colours in the Web Styleguide I think you should let @mtempranoWalla know that is missing this colour

Also this color will be reused or is a particular need?

**Comment by crthc** [comment]
@atomasaltes This is a new color from design that we don't have in this repository and I will need to use it several times

**Comment by mtempranoWalla** [comment]
We've pinged design to see if they can use the ones in the new DS color palette

**Comment by crthc** [comment]
As the design team accepted to use the new DS color palette and the design was changed, this color is no longer needed.

**Pull request closed without merging**
